apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-collector
  namespace: observability
  labels:
    app: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
      annotations:
        configmap-hash: dummy-value  # Will be auto-managed by Kustomize
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - run
            - /etc/alloy/alloy-config.yaml
          ports:
            - containerPort: 12345
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alloy-config-<HASH>  # Kustomize will inject real name
