apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - alloy-config.yaml

generatorOptions:
  disableNameSuffixHash: false  # Enables automatic name like `alloy-config-xxx`
