apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-demo
  labels:
    app: grade-submission-vadi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-submission-vadi
  template:
    metadata:
      labels:
        app: grade-submission-vadi
    spec:
      containers:
      - name: grade-submission-api
        image: rslim087/kubernetes-course-grade-submission-api:stateless
        ports:
          - containerPort: 3000
